version: '3'

services:
  backend:
    container_name: "jarvis_backend"
    image: oracle/glassfish:5.0
    ports:
     - "80:8080"
     - "4848:4848"
    volumes:
     - ./jarvis-backend:/jarvis-backend
     - ./jarvis-backend/out/artifacts/jarvis_backend_war:/glassfish5/glassfish/domains/domain1/autodeploy
    entrypoint: /jarvis-backend/backend-deploy.sh
    links:
      - db
    depends_on:
      - db
  
  db:
    image: mongo:3.2
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user" 
      - MONGODB_PASS="pass1231"
    volumes:
      - ./data:/data
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null