version: '3'

services:
  backend:
    container_name: "jarvis_backend"
    image: oracle/glassfish:5.0
    ports:
     - "3001:8080"
     - "4848:4848"
    volumes:
     - ./jarvis-backend:/jarvis-backend
     - ./jarvis-backend/out/artifacts/jarvis_backend_war:/glassfish5/glassfish/domains/domain1/autodeploy
    entrypoint: asadmin start-domain --verbose
    links:
      - db
      - "rabbit:rabbit"
    depends_on:
      - db
      - rabbit
  
  db:
    image: mongo:3.2
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USR}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null --auth

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: ${RABBIT_USR}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PWD}
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"

volumes:
  db-data:
